### ISSUE TITLE
Plugin seem to not work when instance is on another page

### ISSUE THREAD

**Issue by fakob** [CrookedGrin/maximum-override#5]
Hi
Your plugin looks really promising. 
When testing it today it seemed that it did not work when the instance is on another page.

1. I click the compare instance to main button
2. It says e.g. comparing 64 nodes...
3. Nothing happens

Is there anything I am doing wrong?

**Comment by CrookedGrin** [comment]
Hi, Jakob, thanks for reporting this. Do you mean that the instance is on a different page from the main symbol? It should definitely work in that case. Sounds like there's some other bug (something unusual inside the symbol that I don't have code to catch yet) which is breaking the plugin. Would you be able to share your figma file with me?

**Comment by fakob** [comment]
Hi Michael
Sure, here is the stripped down version of my file. Can't share the complete one, but the bug still seem to exist.
https://www.figma.com/file/XmJjWZctWEAJHAflJbU80Z/Maximum-override-issue?node-id=745%3A4892
Maybe I have some nesting hell going on :-) 
Hope the file helps.

**Comment by fakob** [comment]
You are right, just tried it. If I create a new instance either on the same or new page, everything works fine. Hm, could it have something to do with the frame it is in, prototyping connections etc. Is there a way to diff the response?
History that might help: 
* I have duplicated the whole pages a couple of times as I am doing design iterations
* I might have used the [Replace nodes plugin](https://www.figma.com/community/plugin/748537235829892910/Replace-Nodes) or [Instance Swap](https://www.figma.com/community/plugin/803602060246520783/Instance-Swap). Just tried both of them now and then yours after and everything was still working fine

No idea what could have caused it. Let's file it under "mystery" :-)
Anyway thanks for looking into it. I appreciate that!

**Comment by CrookedGrin** [comment]
No worries, thanks for reporting the issue.
